title: Dave Tello # your name (or website title) here
logo: "/images/DaveFinal.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist/Mathematician
  <br><br>
  I am a committed individual who strives to consistently deliver my best, particularly within the professional sphere. 
  My unwavering dedication drives me to continuously improve my work every day. I possess a deep love for data science 
  as it seamlessly blends two of my long-standing passions: mathematics and programming. With a strong foundation 
  in mathematics, I am able to quickly and comprehensively comprehend new technologies and processes, and possess 
  exceptional analytical skills to solve complex problems.
  <br><br>
  <a href="https://www.linkedin.com/in/david-tello-850a63bb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
