title: Dave Tello # your name (or website title) here
logo: "/images/DaveFinal.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist/Mathematician
  <br><br>
  I consider myself a person who is committed to always give the best, particularly
  in the professional field; I always try to do my job better every day. I love data science 
  as it combines the math and programming that have always been my passion. Having a solid 
  background in mathematics enables me to learn quickly and thoroughly any process or use 
  of new technology as well as a high analytical ability to solve problems.
  <br><br>
  <a href="https://www.linkedin.com/in/david-tello-850a63bb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-hyde
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
