title: Dave Tello # your name (or website title) here
logo: "/images/DaveFinal.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist/Mathematician
  <br><br>
  As an unwaveringly committed individual, I consistently strive to deliver my utmost best, especially in the professional realm. 
  My deep-seated dedication propels me towards continuous improvement on a daily basis. My ardent passion for data science seamlessly 
  integrates two of my long-standing passions: mathematics and programming. My robust mathematical foundation enables me to quickly and 
  comprehensively comprehend novel technologies and processes while furnishing me with exceptional analytical acumen to resolve 
  intricate problems.
  <br><br>
  <a href="https://www.linkedin.com/in/david-tello-850a63bb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
